# services:
#   reservations:
#     build:
#       context: .
#       dockerfile: ./apps/reservations/Dockerfile
#       target: development
#     command: npm run start:dev reservations
#     env_file:
#       - ./apps/reservations/.env
#     ports:
#       - '3000:3000'
#     volumes:
#       - .:/user/src/app
#   auth:
#     build:
#       context: .
#       dockerfile: ./apps/auth/Dockerfile
#       target: development
#     command: npm run start:dev auth
#     env_file:
#       - ./apps/auth/.env
#     ports:
#       - '3001:3001'
#     volumes:
#       - .:/user/src/app
#   payments:
#     build:
#       context: .
#       dockerfile: ./apps/payments/Dockerfile
#       target: development
#     command: npm run start:dev payments
#     env_file:
#       - ./apps/payments/.env
#     ports:
#       - '3003:3003'
#     volumes:
#       - .:/user/src/app
#   mongo:
#     image: mongo

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/user/src/app
    develop:
      watch:
        - action: sync
          path: ./apps/reservations
          target: /user/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/user/src/app
    develop:
      watch:
        - action: sync
          path: ./apps/auth
          target: /user/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/user/src/app
    develop:
      watch:
        - action: sync
          path: ./apps/payments
          target: /user/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/user/src/app
    develop:
      watch:
        - action: sync
          path: ./apps/notifications
          target: /user/src/app

  mongo:
    image: mongo
