FROM node:alpine As development

WORKDIR /user/src/app

COPY package.json ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

COPY apps/payments apps/payments
COPY libs libs

RUN npm install -r

RUN npm run build payments

FROM node:alpine as production 

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /user/src/app

COPY package.json ./

RUN npm install --prod

COPY --from=development /user/src/app/dist ./dist

CMD ["node", "dist/apps/payments/main"]