apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
  labels:
    app: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: europe-west3-docker.pkg.dev/sleepr-427608/reservations/production
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
          ports:
            - containerPort: 3004
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
